#!/usr/bin/env python3
# SourceTracker2 workflow for the Figure 2e glacier-wise mixing analysis
# Reference runtime: Python 3.8.18; see the companion README for package pins.
# Uses fixed Gibbs and rarefaction settings.
# Feature-level assignments are not requested because Figure 2e uses only
# glacier-wise mixing proportions.
#
# ST_otu_table.biom and ST_metadata.csv are generated by
# code/02_community/01_gamm_sourcetracker.R. The first metadata column is
# #SampleID; Group_GI defines sample types and gl_name defines glaciers.

from pathlib import Path
import subprocess
import tempfile

import pandas as pd
from tqdm import tqdm


# --- Configuration ---
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parents[2]
SOURCETRACKER_WORK_DIR = (
    PROJECT_ROOT / "results" / "generated" / "02_community" / "sourcetracker"
)
OUTPUT_DIR = SOURCETRACKER_WORK_DIR / "Results"
BIOM_PATH = SOURCETRACKER_WORK_DIR / "ST_otu_table.biom"
METADATA_PATH = SOURCETRACKER_WORK_DIR / "ST_metadata.csv"

# Parameters used for the Figure 2e primary analysis.
ST2_PARAMS = {
    "burnin": 100,
    "restarts": 10,
    "draws_per_restart": 50,
    "jobs": 8,
    "alpha1": 0.001,
    "alpha2": 0.1,
    "beta": 10,
    "source_rarefaction_depth": 10000,
    "sink_rarefaction_depth": 10000,
}

OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

for input_path in (BIOM_PATH, METADATA_PATH):
    if not input_path.exists():
        raise FileNotFoundError(f"Required input not found: {input_path}")

print("Loading data...")
metadata = pd.read_csv(METADATA_PATH, index_col=0)
sample_type_col = "Group_GI"
gl_name_col = "gl_name"

required_metadata_columns = {sample_type_col, gl_name_col}
missing_metadata_columns = required_metadata_columns.difference(metadata.columns)
if missing_metadata_columns:
    raise ValueError(
        "Metadata is missing required columns: "
        f"{', '.join(sorted(missing_metadata_columns))}"
    )

metadata.index = metadata.index.map(str)

# Run each glacier system separately.
glaciers = metadata[gl_name_col].unique()
print(f"Found {len(glaciers)} glaciers: {', '.join(map(str, glaciers))}")

# For each glacier, ice samples are sources and all other samples are sinks.
# The downstream R analysis uses the sediment sinks shown in Figure 2e.
sample_types = metadata[sample_type_col].unique()
sink_types = [sample_type for sample_type in sample_types if sample_type != "ice"]
print(f"Using 'ice' as source and sinks: {', '.join(map(str, sink_types))}")

sample_types_dict = metadata[sample_type_col].to_dict()
result_frames = []


# --- Main loop ---
for glacier in tqdm(glaciers, desc="Processing glaciers"):
    glacier_mapping = metadata[metadata[gl_name_col] == glacier].copy()
    glacier_mapping = glacier_mapping.reset_index()
    glacier_mapping = glacier_mapping.rename(
        columns={glacier_mapping.columns[0]: "SampleID"}
    )
    glacier_mapping["SampleID"] = glacier_mapping["SampleID"].astype(str)

    glacier_mapping["Env"] = glacier_mapping[sample_type_col]
    glacier_mapping["SourceSink"] = glacier_mapping["Env"].apply(
        lambda value: "source" if value == "ice" else "sink"
    )

    source_count = (glacier_mapping["SourceSink"] == "source").sum()
    sink_count = (glacier_mapping["SourceSink"] == "sink").sum()

    if source_count == 0 or sink_count == 0:
        raise ValueError(
            f"Glacier {glacier} requires at least one ice source and one "
            f"non-ice sink; found {source_count} source and {sink_count} sink."
        )

    # Temporary per-glacier files are deleted after the proportions are read.
    with tempfile.TemporaryDirectory(
        prefix=f"st2_{glacier}_", dir=OUTPUT_DIR
    ) as temp_dir:
        temp_path = Path(temp_dir)
        glacier_mapping_path = temp_path / f"mapping_{glacier}.txt"
        glacier_output_dir = temp_path / f"glacier_{glacier}"
        proportions_path = glacier_output_dir / "mixing_proportions.txt"

        glacier_mapping.to_csv(glacier_mapping_path, sep="\t", index=False)

        # Figure 2e uses mixing_proportions.txt; feature-level assignments are
        # not requested.
        st2_cmd = [
            "sourcetracker2",
            "gibbs",
            "-i",
            str(BIOM_PATH),
            "-m",
            str(glacier_mapping_path),
            "-o",
            str(glacier_output_dir),
        ]
        for name, value in ST2_PARAMS.items():
            st2_cmd.extend([f"--{name}", str(value)])

        subprocess.run(st2_cmd, check=True, cwd=SOURCETRACKER_WORK_DIR)

        if not proportions_path.exists():
            raise FileNotFoundError(
                f"SourceTracker output missing for glacier {glacier}: "
                f"{proportions_path}"
            )

        proportions = pd.read_csv(proportions_path, sep="\t", index_col=0)

        if "ice" in proportions.index or "Unknown" in proportions.index:
            proportions = proportions.T

        melted = proportions.reset_index().melt(
            id_vars="index",
            var_name="Source",
            value_name="Proportion",
        )
        melted.rename(columns={"index": "SampleID"}, inplace=True)
        melted["Glacier"] = glacier
        melted["Group_GI"] = melted["SampleID"].map(sample_types_dict)

        result_frames.append(melted)


# --- Save final output ---
if not result_frames:
    raise RuntimeError("No SourceTracker results were generated.")

all_results = pd.concat(result_frames, ignore_index=True)
output_file = OUTPUT_DIR / "all_results.csv"
all_results.to_csv(output_file, index=False)
print(f"\nCompleted! Final results saved to: {output_file}")
